source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

xcodeproj 'Espressos'

deployment_target = '6.0'

def install_pods
    pod 'TTTAttributedLabel', :path => '../'
end

target :Espressos do
    install_pods
end

target :TTTAttributedLabelTests, :exclusive => true do
    install_pods
    pod 'FBSnapshotTestCase'
    pod 'Expecta'
    pod 'OCMock'
    pod 'KIF'
end
