source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

xcodeproj 'Espressos'

def install_pods
    pod 'TTTAttributedLabel', :path => '../'
end

target :Espressos do
    install_pods
end

target :TTTAttributedLabelTests, :exclusive => true do
    install_pods
    pod 'FBSnapshotTestCase/Core'
    pod 'Expecta'
    pod 'OCMock'
    pod 'KIF'
end
