source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

project 'Espressos'

target :Espressos do
  pod 'TTTAttributedLabel', :path => '../'

  target :TTTAttributedLabelTests do
      inherit! :search_paths
      pod 'FBSnapshotTestCase/Core'
      pod 'Expecta'
      pod 'OCMock'
      pod 'KIF'
  end
end
